[tool.poetry]
name = "dio-bank"
version = "0.1.0"
description = ""
authors = ["ItaloElias <italoelias17@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]
requires-python = ">=3.12"

[tool.poetry.dependencies]
flask = "*"
flask-sqlalchemy = "*"
psycopg2-binary = "*"
gunicorn = "*"

[tool.pytest.ini_options]
addopts = "-ra -vvv"
testpaths = ["test"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
