[project]
name = "dio-bank"
version = "0.1.0"
description = ""
authors = [
    {name = "ItaloElias",email = "italoelias17@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "flask-sqlalchemy"
]


[tool.pytest.ini_options]
addopts = "-ra -vvv"
testpaths = ["test"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
